### ISSUE TITLE
Error with vca(..., method = "Mod")

### ISSUE THREAD

**Issue by bryanhanson** [Chathurga/unmixR#4]
If you do this:
````
load("MUD_A.Rdata") # CB, this was attached to an e-mail I sent
tMod <- vca(data = MUD_A$M, p = 3, method = "Mod") # OK
tMod <- vca(data = MUD_A$M, p = 4, method = "Mod") # gives:
Error in vcaFunc(data, p, ...) : replacement has length zero
````
I've seen this with several larger data sets, not just this one.  Often the function runs for a while before throwing the error. I did not have time to investigate this.

**Comment by cbeleites** [comment]
close -> development moved to gitlab
